### ISSUE TITLE
Access to buckets on AWS and GCP from local computers

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/features#22]
We provide storage buckets for users to write to and setup credentials for them within the user servers started on the hubs. But, what if they want to upload something to those hubs from their local computer or similar - then how do they acquire permissions to do so?

@scottyhq has developed [scottyhq/jupyter-cloud-scoped-creds](https://github.com/scottyhq/jupyter-cloud-scoped-creds) but that [currently has support for AWS S3 buckets but not for GCP buckets](https://github.com/scottyhq/jupyter-cloud-scoped-creds/issues/2).

In practice this ticket _represents significant work_ I think.

### Work items
- [ ] Trial scottyhq/jupyter-cloud-scoped-creds with an AWS S3 bucket
- [x] Figure out how to do the same against GCP buckets
  Resovled by https://github.com/scottyhq/jupyter-cloud-scoped-creds/issues/2#issuecomment-1407476199.
- [x] Figure out what credentials is extracted, are they temporary or long term?
  This should be documented as well, and it would be _very_ good if they are just temporary compared to long term re-usable.
  We rely on GCP's [workload identity](https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity), and AWS's [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), which are mechanisms to couple a k8s ServiceAccount with cloud provider credentials.
  Resolved by https://github.com/scottyhq/jupyter-cloud-scoped-creds/issues/2#issuecomment-1407476199 - they are "short lived" and valid for one hour.
- [ ] Upstream the equivalent for GCP buckets
- [ ] Document use of scottyhq/jupyter-cloud-scoped-creds for AWS and GCP buckets
- [ ] Communicate progress to Julius in https://2i2c.freshdesk.com/a/tickets/387 and Arpita in https://2i2c.freshdesk.com/a/tickets/322

### User requests
- [freshdesk ticket, m2lines, gcp](https://2i2c.freshdesk.com/a/tickets/388)
- [freshdesk ticket, awi-ciroh, gcp](https://2i2c.freshdesk.com/a/tickets/322)

### Maybe related
- 2i2c-org/infrastructure#1980

### Related
- https://github.com/jupyterhub/team-compass/issues/621
- https://github.com/scottyhq/jupyter-cloud-scoped-creds/issues/2
- https://github.com/scottyhq/jupyter-cloud-scoped-creds/issues/4
- https://github.com/scottyhq/jupyter-cloud-scoped-creds/issues/5
- https://github.com/scottyhq/jupyter-cloud-scoped-creds/issues/6
- https://github.com/scottyhq/jupyter-cloud-scoped-creds/issues/7
